environments:
    - name:
      configs:
          endpoints:
              production:
                  url: 'https://petstore.swagger.io/v2/'
              sandbox:
                  url:
          security:
              enabled:
              type:
              username:
              password:
          deploymentEnvironments:
              - displayOnDevportal: true
                deploymentEnvironment: Defalt
                deploymentVhost: localhost
              - displayOnDevportal:
                deploymentEnvironment:  
                deploymentVhost:
          certs:
              - hostName:
                alias:
                path:
              - hostName:
                alias:
                path:
          mutualSslCerts:
              - tierName:
                alias:
                path:
              - tierName:
                alias:
                path:
          policies:
              - 
              -  
